---
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/artifacts/python-library.yaml

variables:
  LANGUAGE_VERSION: python3.8

tox:
  parallel:
    matrix:
      - LANGUAGE_VERSION: [python3.8]
