---
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/artifacts/python-library.yaml


tox:
  parallel:
    matrix:
      - LANGUAGE_VERSION: [python3.7, python3.8, python3.9]
