name: ci
on:
  push:
    branches:
      - develop
      - release/**
      - hotfix/**
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-12
          - macos-13
          - macos-14
          - ubuntu-20.04
          - ubuntu-22.04
          - windows-2019
          - windows-2022
        python:
          - 3.8
    env:
      GDC_CLIENT_ZIP: 'gdc-client.zip'
    steps:
      - uses: actions/checkout@v2
        with:
          # required for setuptools_scm to correctly version: https://github.com/pypa/setuptools_scm/issues/480
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Run Tests
        if: matrix.os != 'windows-latest'
        run: |
          pip install --upgrade pip
          pip install tox
          tox -e py
      - name: Package
        run: |
          cd bin
          pip install virtualenv
          . ./package
          echo "GDC_CLIENT_ZIP=$GDC_CLIENT_ZIP" >> $GITHUB_ENV
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.GDC_CLIENT_ZIP }}-py${{ matrix.python }}-${{ matrix.os }}
          path: bin/gdc-client_*.zip
